config/routes.rb
Rails.application.routes.draw do
  get 'stream' => 'pusher#stream'
  get 'pusher' => 'pusher#index'

  get 'css' => 'css_customier#index'
  post 'css/update' => 'css_customier#update'

  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/css_customier_controller.rb
class CssCustomierController < ApplicationController
  def index
  end

  def update
    css = ""
    css << "$color-success: #{params[:color_success]};" if params[:color_success].present?
    css << "$color-error: #{params[:color_error]};" if params[:color_error].present?
    logger.info css

    begin
      file = File.open(Rails.root.join("app/assets/stylesheets/custom.scss"), "w")
      file.write(css) 
    rescue e
      logger.info e
    ensure
      file.close unless file.nil?
    end

    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  include ActionController::Live

  def stream
    response.headers['Content-Type'] = 'text/event-stream'
    10.times do |i|
      response.stream.write "event: message\n"
      response.stream.write "data: Hello world ##{i+1}\n\n"
      sleep 1
    end

    response.stream.write "event: done\n"
    response.stream.write "data: Done\n\n"
  rescue IOError
    # client disconneted
  ensure
    response.stream.close
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/css_customier/index.html.erb
<h1>Customize Sass Variables</h1>

<%= form_tag css_update_path do |f| %>
  <div>
    <%= label_tag 'color_success' %>
    <%= text_field_tag 'color_success' %>
  </div>

  <div>
    <%= label_tag 'color_error' %>
    <%= text_field_tag 'color_error' %>
  </div>

  <div>
    <%= submit_tag 'Save' %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Stylesheet preview</h1>


<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h3>Heading 3</h3>

<p class='error'>This is an error message.</p>

<p class='success'>This is an message for success.</p>


<%= link_to 'Modify CSS', css_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CustomizeCss</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pusher/index.html.erb
<h1>Pusher#index</h1>

<div id="result">
</div>
 
<%= javascript_tag do %>
  $(function() {
    var eventSource = new EventSource("/stream");

    eventSource.addEventListener("message", function(event) {
      $("#result").text(event.data);
    });
    eventSource.addEventListener("done", function(event) {
      this.close();
      $("#result").text(event.data);
    });
  });
<% end %>